# Generated by Django 5.0.1 on 2024-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_Number',
            field=models.IntegerField(null=True),
        ),
    ]
