# Generated by Django 5.0.1 on 2024-01-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_alter_section_section_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='sectionname',
        ),
    ]
